In [1]:
import numpy as np
import os

save_dir = "features"
if not os.path.exists(save_dir):
    os.mkdir(save_dir)

In [2]:
pos_map = np.load(os.path.join(save_dir, "pos_tags_mappings.npy"), allow_pickle=True)
print(pos_map)
pos = np.load(os.path.join(save_dir, "pos_tags.npy"), allow_pickle=True)
non_punct = [0,1,2,3,4,5,6,7,8,9,10,12,14,15,16,17,18,19,20,21,25,26,27,28,29,30,31,32,33,34,35,36,39]
punct = [i for i in list(range(40)) if i not in non_punct]
print(punct)
print(len(punct))
punct_features = pos[:,punct]
print(punct_features.shape)

{'NNP': 0, 'VBD': 1, 'RB': 2, 'VBN': 3, 'PRP': 4, 'MD': 5, 'VB': 6, 'DT': 7, 'NN': 8, 'RBR': 9, 'IN': 10, ',': 11, 'CC': 12, '.': 13, 'JJ': 14, 'NNS': 15, 'NNPS': 16, 'TO': 17, 'RP': 18, 'JJS': 19, 'WDT': 20, 'VBG': 21, ':': 22, '``': 23, "''": 24, 'WP': 25, 'VBP': 26, 'VBZ': 27, 'WRB': 28, 'PRP$': 29, 'POS': 30, 'CD': 31, 'EX': 32, 'UH': 33, 'WP$': 34, 'JJR': 35, 'PDT': 36, '-LRB-': 37, '-RRB-': 38, 'FW': 39}
[11, 13, 22, 23, 24, 37, 38]
7
(5176, 7)


In [3]:
pos_tags_sans_punct = pos[:,non_punct]
np.save(os.path.join(save_dir, "pos_tags_sans_punct"), pos_tags_sans_punct)

In [4]:
dep = np.load(os.path.join(save_dir, "dep_tags.npy"), allow_pickle=True)
dep_map = np.load(os.path.join(save_dir, "dep_tags_mappings.npy"), allow_pickle=True)
print(dep_map)
punct_dep = dep[:, 10].reshape((-1,1))

{'nsubj': 0, 'aux': 1, 'neg': 2, 'ROOT': 3, 'ccomp': 4, 'det': 5, 'dobj': 6, 'relcl': 7, 'prep': 8, 'pobj': 9, 'punct': 10, 'cc': 11, 'conj': 12, 'mark': 13, 'advcl': 14, 'compound': 15, 'advmod': 16, 'amod': 17, 'xcomp': 18, 'prt': 19, 'acl': 20, 'nmod': 21, 'appos': 22, 'pcomp': 23, 'intj': 24, 'acomp': 25, 'attr': 26, 'npadvmod': 27, 'poss': 28, 'case': 29, 'nummod': 30, 'nsubjpass': 31, 'auxpass': 32, 'oprd': 33, 'agent': 34, 'dative': 35, 'expl': 36, 'dep': 37, 'parataxis': 38, 'predet': 39, 'preconj': 40, 'quantmod': 41}


In [5]:
dep_tags_sans_punct = dep[:,]

In [6]:
punct_final = np.hstack((punct_features, punct_dep))

In [7]:
print(punct_final)
print(punct_final.shape)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]]
(5176, 8)


In [8]:
np.save(os.path.join(save_dir, "punct_final"), punct_final)

In [9]:
pos_tags_sans_punct

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])